const data = [
  {
    id: 1,
    type: 'life',
    title: 'default title No.1',
    content: 'is some text',
    time: '10:00',
    statue: 'general',
    completed: true,
  },
  {
    id: 2,
    type: 'work',
    title: 'default title No.2',
    content: 'is some text',
    time: '10:00',
    statue: 'warning',
    completed: false,
  },
  {
    id: 3,
    type: 'work',
    title: 'default title No.3',
    content: 'is some text',
    time: '10:00',
    statue: 'danger',
    completed: true,
  },
  {
    id: 4,
    type: 'life',
    title: 'default title No.4',
    content: 'is some text',
    time: '10:00',
    statue: 'general',
    completed: true,
  },
  {
    id: 5,
    type: 'life',
    title: 'default title No.5',
    content: 'is some text',
    time: '10:00',
    statue: 'general',
    completed: false,
  },
  {
    id: 6,
    type: 'life',
    title: 'default title No.6',
    content: 'is some text',
    time: '10:00',
    statue: 'danger',
    completed: false,
  },
  {
    id: 7,
    type: 'entertainment',
    title: 'default title No.7',
    content: 'is some text',
    time: '10:00',
    statue: 'general',
    completed: false,
  },
  {
    id: 8,
    type: 'entertainment',
    title: 'default title No.8',
    content: 'is some text',
    time: '10:00',
    statue: 'general',
    completed: true,
  },
  {
    id: 9,
    type: 'entertainment',
    title: 'default title No.9',
    content: 'is some text',
    time: '10:00',
    statue: 'general',
    completed: false,
  },
  {
    id: 10,
    type: 'entertainment',
    title: 'default title No.10',
    content: 'is some text',
    time: '10:00',
    statue: 'general',
    completed: false,
  },
  {
    id: 11,
    type: 'entertainment',
    title: 'default title No.11',
    content: 'is some text',
    time: '10:00',
    statue: 'general',
    completed: false,
  },
];
export default data;
